#!/usr/bin/python
#
# Share By Link: take arbitrary input(s) $* and share them 
# using an appropriate method.
#
# Initial: 5/25/2005 Leo Szumel

import tempfile, sys, re, os, time, urllib, glob, datetime, htmllib
import formatter, urlparse, getopt
#from  Tkinter import Tk

# These are the defaults.
# Put modifications in ~/.jupirc
EXPIRED_DIR = '$HOME/jupi-old' # where expired pages get moved
HTML_MACH = 'machine'      # hostname
HTML_DIR  = 'Html/temp'    # subdir on HTML_MACH where jupi will post
HTML_USER = 'username'     # best set up an ssh key for this
HTML_EXTERNAL_ROOT = 'http://machine/~something/temp' # root pages appear externally
ZIP_ICON = 'path-to-image' # local path to an icon for ZIP files
PAGEAUTH = 'Mr Mister'     # your [pseudo]name
AUTHEMAIL= 'author@domain' # your email address (will be made bot-immunized)
THUMB_W = '256'            # thumbnail constraint (width)
THUMB_H = '256'            # thumbnail constraint (height)
DEF_EXPIRY = 7             # days to expiration  (0 for never)
RCFILE = '.jupirc'         # name of .rc file (can override any globals)
THUMBTYPE = '.png'         # thumbnail format for INDEXED images 
                           # (canuse .gif for MacOS)
                           # .jpg is always used for TrueColor/Grayscale images
RCROOTS = ['~/','./']      # places to look for RCFILE

for rcc in [os.path.expanduser(r + RCFILE) for r in RCROOTS]:
  if os.path.exists(rcc):
    try:    exec open(rcc).read()
    except: print '!!! Problem with ' + rcc

# for safe debugging
def ossystem(str):
  print 'os.system ' + str

def ospopen(str):
  print 'os.popen ' + str

def getTinyurl(url):
  '''return a tinyurl if possible, else the url'''
  try:
    h = urllib.urlopen('http://www.tinyurl.com/create.php?url=' + url).read()
    turl = re.search('<a href=\"(http://tinyurl.com/[^"]+)', h).group(1)
  except:
    turl = url
  return turl

def bytesToGeek(size):
   '''return a string representing the greek/metric suffix of a size
    from http://mail.python.org/pipermail/python-list/1999-December/018406.html
   '''
   _abbrevs = [ (1<<50L, 'P'), (1<<40L, 'T'), (1<<30L, 'G'), (1<<20L, 'M'), 
    (1<<10L, 'k'), (1, 'B') ]
   for factor, suffix in _abbrevs:
     if size > factor: break
   return str(int(size/factor)) + suffix 

class SomethingToPost:
  ''' Container for an object to post online
      should define:
      
      fname   -- name of object
      type    -- type of object
      file    -- temporary file name (will be posted)
                 * this can be used as a scratch file intermediately
      pfile   -- file representing a preview of the object
      text    -- textual description of the object
  '''
      
  def __init__(self, fname, postdir):
    self.fname = fname.replace(' ','\ ')
    self.fname = self.fname.replace('|','\|')
    self.type = os.path.splitext(fname)[1].lower()
    self.dir  = postdir
    self.file = '%s/%s' % (self.dir, os.path.basename(fname))
    self.file = self.file.replace(' ','_')
    self.file = self.file.replace('|','_')
    typetest  = os.popen4('identify -verbose ' + self.fname + '[0]')[1].read()
    m = re.search('[:space:]*Type: (.*)', typetest) 
    if m and m.group(1) in 'Grayscale TrueColor':
      suffix = '.jpg'
    else:
      suffix = THUMBTYPE
    fid,self.pfile = tempfile.mkstemp(dir=self.dir, suffix=suffix)
    os.close(fid)

  def thumbnailByConvert(self, source, rescale=1):
    ''' Standard preview via imagemagick convert '''
    if rescale: size = '-resize %sx%s\>' % (THUMB_W, THUMB_H)
    else:       size = ''
    os.system('convert %s[0] %s -frame 3x3 %s' % (
      source, size, self.pfile))

  def thumbnailOfType(self):
    ''' Standard preview for un-convertable files '''
    os.system('convert -size 96x64 xc:transparent -font Arial.ttf -pointsize 32 -stroke magenta -draw "text 10,45 \'%s\'" -frame 3x3 %s' % (
      self.type or ' ? ', self.pfile))

  def post(self, postdir, index):
    ''' return fields for HTML code; use relative paths '''
    file  = os.path.basename(self.file)
    pfile = os.path.basename(self.pfile)
    size  = bytesToGeek(os.path.getsize(self.file))
    return {'file':file, 'img':pfile, 'text':self.text, 'size':size}

class ZIP(SomethingToPost):
  ''' zip archive
  '''
  def __init__(self, fname, postdir):
    SomethingToPost.__init__(self, fname, postdir)

  def prep(self):
    ''' test all and post 5 files '''
    if os.path.exists(os.path.expanduser(ZIP_ICON)): 
      self.thumbnailByConvert(ZIP_ICON)
    else:
      self.thumbnailOfType()
    self.text = os.popen('unzip -t %s | grep testing | head -5' % self.fname).read()
    os.system('cp %s %s' % (self.fname, self.file))

    return [self]

class Text(SomethingToPost):
  ''' Any text file that a2ps can handle
  '''
  def __init__(self, fname, postdir, a2psfile=None):
    SomethingToPost.__init__(self, fname, postdir)
    self.a2psfile = a2psfile

  def prep(self):
    viewfile = self.a2psfile or self.fname
    os.system('a2ps %s --prologue=color --portrait --columns=1 --pages=1 --pretty-print --delegate=0 -o - | convert - -crop 256x128+0+25 %s' % (viewfile, self.pfile))
    self.thumbnailByConvert(self.pfile, rescale=0)
    self.text = os.popen('head -5 %s | cut -c1-40' % viewfile).read()
    os.system('cp %s %s' % (self.fname, self.file))
 
    return [self]

class WordDoc(Text):
  ''' A MS Word file. Convert to plain text.
  '''
  def __init__(self, fname, postdir):
    docf,docn = tempfile.mkstemp(dir='/tmp/', suffix='.txt')
    os.system('catdoc %s > %s' % (fname, docn))
    os.close(docf)
    Text.__init__(self, fname, postdir, a2psfile=docn)

class Excel(Text):
  ''' A MS Excel. Convert to .csv and treat as Text.
  '''
  def __init__(self, fname, postdir):
    csvf,csvn = tempfile.mkstemp(dir='/tmp/', suffix='.csv')
    os.system('xls2csv %s > %s' % (fname, csvn))
    os.close(csvf)
    Text.__init__(self, fname, postdir, a2psfile=csvn)

class PS(SomethingToPost):
  ''' Postscript (PS) files
  '''
  def __init__(self, fname, postdir):
    SomethingToPost.__init__(self, fname, postdir)

  def prep(self):
    ''' grab the first page, reduce and frame it '''
    self.thumbnailByConvert(self.fname)
    os.system('cp %s %s' % (self.fname, self.file))
    
    self.text = os.popen('ps2ascii %s | head -8 | cut -c1-40' % self.file).read()
 
    return [self]

class PDF(SomethingToPost):
  ''' Acrobat (PDF) files
  '''
  def __init__(self, fname, postdir):
    SomethingToPost.__init__(self, fname, postdir)

  def prep(self):
    ''' grab the first page, reduce and frame it '''
    self.thumbnailByConvert(self.fname)
    os.system('cp %s %s' % (self.fname, self.file))
    
    self.text = os.popen('pdfinfo %s | egrep \"version|Page\"' % self.file).read()
    self.text += os.popen('ps2ascii %s | head -8 | cut -c1-40' % self.file).read()
 
    return [self]

class Image(SomethingToPost):
  ''' Any images that imagemagick can handle
  '''
  def __init__(self, fname, postdir):
    SomethingToPost.__init__(self, fname, postdir)

  def prep(self):
    ''' Reduce to reasonable browser size '''
    os.system('convert -size 1024x768 %s -resize 1024x768\> %s' % (
        self.fname, self.file))
    self.thumbnailByConvert(self.fname)
    os.system('cp %s %s' % (self.fname, self.file))
    
    self.text = os.popen('identify -format \'%%wx%%h %%e\' %s[0]' % self.file).read()
    if self.type == '.jpg':
      self.text += os.popen('jhead %s | egrep \"Date|model|Flash|Focal|Exposure|Aperture|ISO\"' % self.file).read()
 
    return [self]

class NONE(Text):
  ''' For everything else, there's MasterCard
      Subclass from Text in case we think this contains text
      Should I use unix 'strings' ???
  '''
  def __init__(self, fname, postdir):
    Text.__init__(self, fname, postdir)

  def prep(self):
    ''' Just link to it '''
    os.system('cp %s %s' % (self.fname, self.file))
    self.thumbnailOfType()
    sample = os.popen('head -5 %s' % self.file).read()[:100].strip()
    if re.search('^#!/', sample):
      Text.prep(self)
    else:
      if sample.replace(' ','').isalnum():
        self.text = sample
      else:
        self.text = 'No preview for file type %s' % self.type

    return [self]

class HTML(NONE):
  ''' HTML code
  '''
  def __init__(self, fname, postdir):
    NONE.__init__(self, fname, postdir)

  def prep(self):
    ''' Goal here is to grab links for the text preview  '''
    Text.prep(self)
    
    html = open(self.file).read()
    p = htmllib.HTMLParser(formatter.NullFormatter())
    p.feed(html)
    p.close()
    urls = {}
    for u in [u for u in p.anchorlist if u[0:4] == 'http']:
      urls[u] = urls.get(u, 0) + 1
    urlfreqs = [(f,u) for (u, f) in urls.items()]
    urlfreqs.sort()
    self.text = ''
    for (f,u) in urlfreqs[0:5]:
      self.text += '<a href=\"%s\">%s</a>\n' % (u, u[0:30])
 
    return [self]

def usage():
  print 'Usage: jupi [list of files and/or directories]'
  print '-b (do not generate tinyurl)'
  print '-c (put url to clipboard)'
  print '-e days-from-now (delete files automatically using "at")'
  print '-t (test mode--do not upload any files)'

if __name__ == '__main__':
  stps = []
  postdir = tempfile.mkdtemp()
  opts, todo = getopt.getopt(sys.argv[1:], 'hbce:t')
  options = dict(opts)

  # Preprocess/check arguments
  expiry= DEF_EXPIRY
  
  if not len(todo):
    usage()
    sys.exit()

  for o,a in options.items():
    if o in ('-h','--help'):
      usage()
      sys.exit()
    elif o == '-e':
      try: expiry= int(a)
      except: print 'Invalid argument to -e:',a
    elif o == '-b':
      pass
    elif o == '-c':
      pass
    elif o == '-t':
      print 'TEST MODE: NO FILES WILL BE POSTED'

  # Expiry handling:
  expirydate = (datetime.timedelta(expiry) + datetime.date.today())
  indexf,indexn = tempfile.mkstemp(dir=postdir, suffix='.html')
  postpath = os.path.join('$HOME/',HTML_DIR, os.path.basename(postdir))
  ef = ('#' + expirydate.isoformat() + '\n' + 
       'mkdir -p %s; mv %s %s\n' % (EXPIRED_DIR, postpath, EXPIRED_DIR))
  open(os.path.join(postdir,'.expiry'),'w').write(ef)
  if expiry: expirystring = expirydate.strftime('%A, %B %d, %Y') 
  else:      expirystring = 'never'

  # Pick a URL and create big/tiny version for user:
  longurl = '%s/%s/%s' % (HTML_EXTERNAL_ROOT,
      os.path.basename(postdir), os.path.basename(indexn))
  if not '-b' in options:
    tinyurl = getTinyurl(longurl)
    purl = tinyurl
  else:
    purl = longurl
  print 'Files will expire %s and be placed at:\n%s' % (expirystring, purl)

  # Handle each file:
  for t in todo:
    #t = t.replace('|', '\|')
    print t
    if os.path.isdir(t):
      todo.extend(glob.glob(t+'/*'))
      continue
    try:
      type = os.path.splitext(t)[1].lower()
      if type == '.ps':
        stp = PS(t, postdir)
      elif type == '.pdf':
        stp = PDF(t, postdir)
      elif type == '.zip':
        stp = ZIP(t, postdir)
      elif type == '.xls':
        stp = Excel(t, postdir)
      elif type == '.doc':
        stp = WordDoc(t, postdir)
      elif type in ['.txt','.py','.rb','.cpp','.c','.h']:
        stp = Text(t, postdir)
      elif type in ['.html','.htm']:
        stp = HTML(t, postdir)
      # handle other types here, before default
      else:
        test = os.popen4('identify -verbose ' + t + '[0]')[1].read()
        if re.search('decode delegate|Improper|Unable|missing an image',
            test):
          raise Exception
        else:
          stp  = Image(t, postdir)
    except:
      print 'Sorry, don\'t know what to do with ' + t
      stp = NONE(t, postdir)
    for s in stp.prep():
        stps.append(s)
  
  # Generate HTML:
  os.write(indexf, '''
    <html><body><center>
    <meta name=\"Generator\" content=\"Python script\">
    <meta name=\"ROBOTS\" content=\"NOINDEX, NOFOLLOW\">
    <title>A quick note to you from %s</title>
    <h3>A quick note to you from %s</h3>
    <p><i>Be careful when linking to this page (expires %s)</i></p>
    <hr width=50%%>
    <table border=\"0\" width=\"66%%\" cellspacing=\"10\">''' % (
      PAGEAUTH, PAGEAUTH, expirystring))#'%A %B %d %Y'

  template = '''
    <tr>
      <td align=\"right\">
        <a href=\"%(file)s\">
        <img border=0 src=\"%(img)s\" alt=\"%(file)s\"></img> </a>
      </td>
      <td>
        <a href=\"%(file)s\">%(file)s (%(size)s)</a><br>
        <pre>%(text)s</pre>
      </td>
    </tr>'''
  
  for s in stps:
    os.write(indexf, template % s.post(postdir, indexf))
     
  mailto = AUTHEMAIL.split('@')
  os.write(indexf, '''
    </table><hr width=50%%>
    <BR><small>
      Generated on behalf of 
      <script language="javascript">
        <!-- 
        var domain = "%s"
        var mail = "mail" + "to:" + "%s@" + domain 
        document.write("<a href=\\"" + mail + "\\" class=\\"nav\\">");
        document.write("%s");
        document.write("</a>");
        // -->
      </script>
      using <a href="http://jupi.berlios.de">jupi 0.1</a>. %s.<br>
    </small>
    </center></body></html> ''' % (mailto[1], mailto[0], PAGEAUTH, 
      time.asctime()))
  os.close(indexf)
  os.system('chmod -R a+rx ' + postdir)
  if not '-t' in options:
    os.system('scp -rp %s %s@%s:%s' % (postdir, HTML_USER, HTML_MACH, HTML_DIR))
    if expiry:
      os.system('ssh %s@%s at 23:59 + %d days -f %s' % (HTML_USER, HTML_MACH, expiry, os.path.join(HTML_DIR, os.path.basename(postpath), '.expiry')))
  # Handle additional options
  if '-c' in options:
    try:
#      root = Tk()
#      root.clipboard_clear()
#      root.clipboard_append(tinyurl)
      print 'copied to clipboard.'
    except: pass
  print 'That URL again is:\n',purl
  
   
